# Generated by Django 5.2.8 on 2025-11-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(default=False, help_text='Отмечайте, если пользователь является менеджером', verbose_name='manager status'),
        ),
    ]
